image: node:16

definitions:
  caches:
    node: /usr/local/share/.cache/yarn/v6

  variables:
    # Global default environment variables
    CI: 'true'
    REACT_APP_VERSION: $npm_package_version
    REACT_APP_NAME: $npm_package_name
    NODE_ENV: 'production'
    NEXT_PUBLIC_ENV: 'dev'

  scripts:
    - step: &step-install-test-build
        name: Install dependencies, run tests and build app
        caches:
          - node
        script:
          # We want to install all dependencies, including devDependencies
          - yarn install --frozen-lockfile --production false
          - yarn test
          - yarn build
        variables:
          # Default environment variables for build
          NEXT_PUBLIC_SITE_URL: 'http://localhost:3000'

    - step: &step-build-storybook
        name: Build Storybook
        caches:
          - node
        script:
          - yarn install --frozen-lockfile --production false
          - yarn build-storybook

pipelines:
  branches:
    master:
      - step: *step-install-test-build
        variables:
          NEXT_PUBLIC_ENV: 'prod'
          NEXT_PUBLIC_SITE_URL: 'https://graduate.columbusglobal.com'

  pull-requests:
    '**':
      - step: *step-install-test-build
      - step: *step-build-storybook
        condition: changeset('.storybook/**') || changeset('**/*.stories.tsx')
